modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/KubeJS-Mods/KubeJS/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs"
version = "${version}"
displayName = "KubeJS"
authors = "LatvianModder"
description = '''
Customize your modpack or server with JavaScript!
'''
logoFile = "kubejs_logo.png"
license = "GNU LGPLv3"

[[dependencies.kubejs]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs]]
modId = "rhino"
mandatory = true
versionRange = "[1800.1.6-build.76,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "architectury"
mandatory = true
versionRange = "[2.5.32,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "jei"
mandatory = false
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"