modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://kubejs.com/support?source=kubejs&mc=2001&loader=forge"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs"
version = "${version}"
displayName = "KubeJS"
authors = "LatvianModder"
description = '''
Customize your modpack or server with JavaScript!
'''
logoFile = "kubejs_logo.png"
license = "GNU LGPLv3"

[[dependencies.kubejs]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs]]
modId = "rhino"
mandatory = true
versionRange = "[${min_rhino_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "jei"
mandatory = false
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[9.1.572,)"
ordering = "AFTER"
side = "BOTH"