name: Java CI

on:
  push:
    branches:
      # main and dev versions for each mc ver here
      - "1.16/main"
      - "1.16/dev"
  workflow_dispatch:
    inputs:
      norelease:
        description: 'Do not publish'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
        with:
          fetch-depth: 30 # Gets the last 30 commits so the changelog might work
      # Always run on Java 16, Loom needs it
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build with Gradle
        env:
          FTB_MAVEN_TOKEN: ${{ secrets.FTB_MAVEN_TOKEN }}
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish --stacktrace --no-daemon
      - name: Release to CurseForge
        if: |
          contains(github.ref, 'main') && !contains(github.event.head_commit.message, '[norelease]') && github.event.inputs.norelease != 'true'
        env:
          GIT_COMMIT: ${{ github.event.after }}
          GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew build curseforge --stacktrace --no-daemon